Repository andela/Lit-Kigali1-Frontend, pull requests merged in 2019-05, with the labels that each got.

#18 #163519113 Implement article's search
  .eslintrc
  .gitignore
  package.json
  src/__mocks__/dummyData.js
  src/__tests__/_components/Routes.test.js
  src/__tests__/actions/articleActions.test.js
  src/__tests__/actions/currentUserActions.test.js
  src/__tests__/components/Article.test.js
  src/__tests__/components/ArticleCard.test.js
  src/__tests__/components/Articles.test.js
  src/__tests__/components/ArticlesCurrentUser.test.js
  src/__tests__/components/ConfirmedEmailEmail.test.js
  src/__tests__/components/ConfirmedEmailMessage.test.js
  src/__tests__/components/Dislikes.test.js
  src/__tests__/components/Likes.test.js
  src/__tests__/components/NavBar.test.js
  src/__tests__/components/Pagination.test.js
  src/__tests__/components/ProfileEdit.test.js
  src/__tests__/components/ProfileView.test.js
  src/__tests__/components/Ratings.test.js
  src/__tests__/components/common/DeleteModal.test.js
  src/__tests__/components/common/SearchInput.test.js
  src/__tests__/helpers/editorPlugins/addLink.test.js
  src/__tests__/helpers/editorPlugins/highlight.test.js
  src/__tests__/helpers/mediaBlockRenderer.test.js
  src/__tests__/reducers/articleReducer.test.js
  src/__tests__/reducers/currentUserReducer.test.js
  src/_styles/cards/_ArticleCard.scss
  src/_styles/pages/_ArticleCreate.scss
  src/_styles/pages/_Articles.scss
  src/_styles/pages/_Home.scss
  src/_styles/pages/_Login.scss
  src/_styles/style.scss
  src/components/Article/Article.jsx
  src/components/Article/ArticleCard.jsx
  src/components/Article/Articles.jsx
  src/components/Article/ArticlesCurrentUser.jsx
  src/components/Auth/SignUp.jsx
  src/components/NavBar/NavBar.jsx
  src/components/Routes.jsx
  src/components/common/ErrorPage/ErrorPage.jsx
  src/components/common/Input/SearchInput.jsx
  src/components/common/Modal/DeleteModal.jsx
  src/components/common/Pagination.jsx
  src/redux/actions-types/articleTypes.js
  src/redux/actions/articleActions.js
  src/redux/initialState.js
  src/redux/reducers/articleReducer.js
  src/redux/reducers/currentUserReducer.js
  src/redux/reducers/forgotPasswordReducer.js
  src/redux/reducers/loginReducer.js
  src/redux/reducers/signUpReducer.js
  src/redux/reducers/userReducer.js
  src/redux/store/index.js
Labels: ready just merge conflicts

#19 #163519109 share article social
  enzyme.config.js
  package.json
  src/__tests__/actions/currentUserActions.test.js
  src/__tests__/components/Article.test.js
  src/__tests__/components/ProfileEdit.test.js
  src/__tests__/reducers/articleReducer.test.js
  src/_styles/base/_typography.scss
  src/_styles/pages/_Article.scss
  src/_styles/style.scss
  src/components/Article/Article.jsx
  src/redux/actions-types/articleTypes.js
  src/redux/actions/articleActions.js
  src/redux/reducers/articleReducer.js
  webpack.config.js
Labels: ready just merge conflicts

#22 #163519108 Implement filter by tags when viewing an article
  src/__tests__/components/Article.test.js
  src/__tests__/components/ConfirmedEmailEmail.test.js
  src/__tests__/helpers/editorPlugins/addLink.test.js
  src/__tests__/helpers/mediaBlockRenderer.test.js
  src/__tests__/reducers/articleReducer.test.js
  src/_styles/pages/_Article.scss
  src/components/Article/Article.jsx
  src/redux/reducers/articleReducer.js
  webpack.config.js
Labels: ready just merge conflicts, ready to be merged

#23 #163519120 Add like and dislike a comment
  src/__mocks__/dummyData.js
  src/__tests__/actions/commentAction.test.js
  src/__tests__/actions/currentUserActions.test.js
  src/__tests__/components/Article.test.js
  src/__tests__/components/Comment.test.js
  src/__tests__/components/CommentRender.test.js
  src/__tests__/components/ProfileEdit.test.js
  src/__tests__/reducers/commentReducer.test.js
  src/_styles/base/_colors.scss
  src/_styles/pages/_Article.scss
  src/_styles/style.scss
  src/components/Article/Article.jsx
  src/components/Comment/Comment.jsx
  src/components/Comment/CommentRender.jsx
  src/components/Profile/ProfileEdit.jsx
  src/components/Profile/ProfileView.jsx
  src/redux/actions-types/commentTypes.js
  src/redux/actions/articleActions.js
  src/redux/actions/commentAction.js
  src/redux/initialState.json
  src/redux/reducers/commentReducer.js
Labels: ready to be merged

#25 #165571064 Add landing and home pages
  package.json
  src/__mocks__/dummyData.js
  src/__tests__/_components/Routes.test.js
  src/__tests__/actions/articleActions.test.js
  src/__tests__/components/Article.test.js
  src/__tests__/components/Home.test.js
  src/__tests__/reducers/articleReducer.test.js
  src/_styles/cards/_ArticleCard.scss
  src/_styles/pages/_Home.scss
  src/_styles/style.scss
  src/components/Article/Article.jsx
  src/components/Home/Home.jsx
  src/components/NavBar/NavBar.jsx
  src/redux/actions-types/articleTypes.js
  src/redux/actions/articleActions.js
  src/redux/initialState.js
  src/redux/reducers/articleReducer.js
Labels: ready just merge conflicts

#28 #163519112 Implement notifications opt-in/out
  src/__tests__/actions/currentUserActions.test.js
  src/__tests__/components/settings.test.js
  src/__tests__/reducers/currentUserReducer.test.js
  src/_styles/base/_toggleIcon.scss
  src/_styles/base/_variables.scss
  src/_styles/pages/_settings.scss
  src/_styles/style.scss
  src/components/Routes.jsx
  src/components/Settings/Settings.jsx
  src/redux/actions-types/currentUserTypes.js
  src/redux/actions/currentUserActions.js
  src/redux/actions/loginActions.js
  src/redux/initialState.js
  src/redux/reducers/currentUserReducer.js
Labels: In review
